version: '3.7'
services:
  interlok:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      JAVA_OPTS:
    depends_on:
      localstack:
        condition: service_healthy
  localstack:
    image: localstack/localstack:3.6.0
    hostname: localstack-1
    environment:
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DEBUG=1 # Optional: for more detailed logs
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
#    ports:
#        - "127.0.0.1:4566:4566"            # LocalStack Gateway
#        - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
    healthcheck:
      test:  >-
        awslocal sqs list-queues
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 10
volumes:
  storage-group: